# String
company = "Microdegree"
print(company)
print(company[0])
print(company[1])
print(company[2])
print(company[3])
print(company[4])
print(company[5])
print(company[6])
print(company[7])
print(company[8])
print(company[9])
print(company[10])

print(company[-1])
print(company[-2])
print(company[-3])
print(company[-4])
print(company[-5])
print(company[-6])
print(company[-7])
print(company[-8])
print(company[-9])
print(company[-10])
print(company[-11])
